name: motor_mania
description: "Unlock the world of Automotive Treasures."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  bot_toast: ^4.1.3
  carousel_slider: ^4.2.1
  colorful_safe_area: ^1.0.0
  cupertino_icons: ^1.0.6
  dartz: ^0.10.1
  dio: ^5.4.3+1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  flutter_bloc: ^8.1.6
  flutter_native_splash: ^2.4.0
  flutter_screenutil: ^5.9.3
  flutter_secure_storage: ^9.2.2
  flutter_svg: ^2.0.10+1
  gap: ^3.0.1
  get_it: ^7.7.0
  lottie: ^3.1.2
  persistent_bottom_nav_bar_v2: ^5.2.3
  pretty_dio_logger: ^1.3.1
  shimmer: ^3.0.0

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/images/
    - assets/icons/
    - assets/animation/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-ExtraBold.ttf
          style: normal
          weight: 800

        - asset: assets/fonts/Montserrat-Bold.ttf
          style: normal
          weight: 700

        - asset: assets/fonts/Montserrat-SemiBold.ttf
          style: normal
          weight: 600

        - asset: assets/fonts/Montserrat-Medium.ttf
          style: normal
          weight: 500

        - asset: assets/fonts/Montserrat-Regular.ttf
          style: normal
          weight: 400
